-- EJERCICIO 1
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID > 10
ORDER BY LAST_NAME;

-- EJERICICIO 2
SELECT LAST_NAME, FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE LAST_NAME = 'Whalen';

-- EJERCICIO 3
SELECT EMPLOYEE_ID, LAST_NAME AS "Apellido", FIRST_NAME AS "Nombre"
FROM EMPLOYEES
ORDER BY EMPLOYEE_ID DESC;


-- EJERCICIO 4
SELECT LAST_NAME || ' ' || FIRST_NAME AS "Apellido y Nombre", HIRE_DATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (100, 200);

-- EJERCICIO 5
SELECT *
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'A%';

-- EJERCICIO 6
SELECT DISTINCT LAST_NAME
FROM EMPLOYEES;

-- EJERCICIO 7
SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT';

-- EJERCICIO 8
SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY != 2500;

-- EJERCICIO 9
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID BETWEEN 40 AND 100;

-- EJERCICIO 10
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

-- EJERCICIO 11
SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (100, 101);

-- EJERCICIO 12
SELECT E.EMPLOYEE_ID, E.LAST_NAME, E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID = 50;

-- EJERCICIO 13
SELECT COUNT(*) AS "Cantidad de empleados"
FROM EMPLOYEES;

-- EJERCICIO 14
SELECT E.LAST_NAME, E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE UPPER(E.LAST_NAME) LIKE '_O%';
-- tambien podria ser con substring

-- EJERCICIO 15
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;

-- EJERCICIO 16
SELECT MAX(SALARY) - MIN(SALARY) AS "Diferencia"
FROM EMPLOYEES;

-- EJERCICIO 17
SELECT COUNT(DISTINCT DEPARTMENT_ID)
FROM EMPLOYEES;

-- EJERCICIO 18
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 5;

-- EJERCICIO 19
SELECT E.*
FROM EMPLOYEES E
WHERE E.SALARY = (
      SELECT MIN(E1.SALARY)
      FROM EMPLOYEES E1
);

-- EJERCICIO 20
SELECT
   ROUND(AVG(E.SALARY), 2) AS "Salario Promedio",
   D.DEPARTMENT_ID,
   D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME ;

-- EJERCICIO 21
SELECT *
FROM DEPARTMENTS D
WHERE (
      SELECT COUNT(*)
      FROM EMPLOYEES E
      WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
) = 0;
-- o tambien
SELECT *
FROM DEPARTMENTS D
WHERE D.DEPARTMENT_ID NOT IN (
      SELECT DISTINCT E.DEPARTMENT_ID
      FROM EMPLOYEES E
);

-- EJERCICIO 22
SELECT
   MIN(E.SALARY),
   E.DEPARTMENT_ID,
   E.JOB_ID
FROM EMPLOYEES E
GROUP BY E.DEPARTMENT_ID, E.JOB_ID;

-- EJERCICIO 23
SELECT E.*
FROM EMPLOYEES E
WHERE E.SALARY > (
      SELECT E1.SALARY
      FROM EMPLOYEES E1
      WHERE E1.EMPLOYEE_ID = 101
);

-- EJERCICIO 24
SELECT E.*
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID = 50
      AND E.SALARY > (
          SELECT E1.SALARY
          FROM EMPLOYEES E1
          WHERE E1.EMPLOYEE_ID = 120
      );
