-- EJERCICIO 1
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 5000 AND 12000;

-- EJERCICIO 2
SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '20/02/1998' AND '01/05/1998'
ORDER BY HIRE_DATE;

-- EJERCICIO 3
SELECT E.LAST_NAME, J.JOB_TITLE
FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE E.MANAGER_ID IS NULL;

-- EJERCICIO 4
SELECT LAST_NAME
FROM EMPLOYEES
WHERE UPPER(LAST_NAME) LIKE '%A%' AND UPPER(LAST_NAME) LIKE '%E%';

-- EJERCICIO  5
SELECT DISTINCT J.JOB_TITLE, L.STREET_ADDRESS || ', ' || L.CITY AS "Ubicacion"
FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID
     JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
     JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE D.DEPARTMENT_ID = 80;

-- EJERCICIO 6
SELECT
   E.LAST_NAME,
   E.FIRST_NAME,
   D.DEPARTMENT_NAME,
   L.LOCATION_ID,
   L.CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
     JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.COMMISSION_PCT IS NOT NULL OR E.COMMISSION_PCT > 0;

-- EJERCICIO 7
SELECT
   E.LAST_NAME,
   J.JOB_TITLE,
   L.LOCATION_ID,
   D.DEPARTMENT_NAME,
   L.CITY
FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID
     JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
     JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE UPPER(L.CITY) = 'TORONTO';

-- EJERCICIO 8
SELECT
   E.LAST_NAME AS "Emp#",
   D.DEPARTMENT_ID AS "Cod Dep",
   D.DEPARTMENT_NAME AS "Descrip Dep"
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- EJERCICIO 9
SELECT
   COUNT(DISTINCT MANAGER_ID) AS "Number of Managers"
FROM EMPLOYEES;

-- EJERCICIO 10
SELECT
   MAX(SALARY) - MIN(SALARY) AS "DIFFERENCE"
FROM EMPLOYEES;

-- EJERCICIO 11
SELECT E2.EMPLOYEE_ID, MIN(E1.SALARY)
FROM EMPLOYEES E1 JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID
WHERE E1.EMPLOYEE_ID IS NOT NULL
GROUP BY E2.EMPLOYEE_ID
HAVING MIN(E1.SALARY) >= 6000
ORDER BY MIN(E1.SALARY) DESC;

-- EJERCICIO 12
SELECT E.DEPARTMENT_ID
FROM EMPLOYEES E
WHERE E.JOB_ID != 'ST_CLERK'
GROUP BY E.DEPARTMENT_ID;

-- EJERCICIO 13
SELECT E.EMPLOYEE_ID, E.DEPARTMENT_ID
FROM EMPLOYEES E
UNION
SELECT E.EMPLOYEE_ID, D.DEPARTMENT_ID
FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- EJERCICIO 14
SELECT E.LAST_NAME, E.HIRE_DATE
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID = (
      SELECT E1.DEPARTMENT_ID
      FROM EMPLOYEES E1
      WHERE E1.LAST_NAME = 'Zlotkey'
) AND E.LAST_NAME != 'Zlotkey';

-- EJERCICIO 15
SELECT E.EMPLOYEE_ID, E.LAST_NAME
FROM EMPLOYEES E
WHERE E.SALARY > (
      SELECT AVG(E1.SALARY)
      FROM EMPLOYEES E1
)
ORDER BY E.SALARY ASC;

-- EJERCICIO 16
SELECT E.LAST_NAME, E.DEPARTMENT_ID, E.SALARY
FROM EMPLOYEES E
WHERE (E.DEPARTMENT_ID, E.SALARY) IN (
      SELECT E1.DEPARTMENT_ID, E1.SALARY
      FROM EMPLOYEES E1
      WHERE E1.COMMISSION_PCT IS NOT NULL
            OR E1.COMMISSION_PCT > 0
);
-- o tambien
SELECT E.LAST_NAME, E.DEPARTMENT_ID, E.SALARY
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID IN (
      SELECT E1.DEPARTMENT_ID
      FROM EMPLOYEES E1
      WHERE E1.COMMISSION_PCT IS NOT NULL
            OR E1.COMMISSION_PCT > 0
) AND E.SALARY IN (
      SELECT E2.SALARY
      FROM EMPLOYEES E2
      WHERE E2.COMMISSION_PCT IS NOT NULL
            OR E2.COMMISSION_PCT > 0
);

-- EJERCICIO 17
SELECT E.*
FROM EMPLOYEES E
WHERE E.SALARY > ALL (
      SELECT E1.SALARY
      FROM EMPLOYEES E1
      WHERE E1.JOB_ID = 'SA_MAN'
)
ORDER BY E.SALARY DESC;

-- EJERCICIO 18
SELECT
   E.LAST_NAME AS "Apellido",
   E.DEPARTMENT_ID AS "Id de Depto",
   ROUND(A.AVG_DEPARTMENT_SALARY, 2) AS "Salario Promedio de Depto"
FROM EMPLOYEES E INNER JOIN (
     SELECT E1.DEPARTMENT_ID, AVG(E1.SALARY) AS "AVG_DEPARTMENT_SALARY"
     FROM EMPLOYEES E1
     GROUP BY E1.DEPARTMENT_ID
) A ON E.DEPARTMENT_ID = A.DEPARTMENT_ID
WHERE E.SALARY > A.AVG_DEPARTMENT_SALARY
ORDER BY A.AVG_DEPARTMENT_SALARY;
